Added Darkbox loading fullsized images animation
failed-successfully/ngx-darkbox-gallery-library pull request #96
Opened 2021-05-09 15:03 UTC by hramberger

Closes #95

2021-05-13 16:22 UTC, hramberger commented
This should be merged after #68

2021-05-17 21:22 UTC, Boerni1995 requested changes

2021-05-17 21:22 UTC, Boerni1995 commented on README.md
> +| SQUARE    | A line of jumping squared moving in a wave like form  |
```suggestion
| SQUARE    | A line of jumping squares moving in a wave like form  |
```

2021-05-17 21:22 UTC, Boerni1995 commented on projects/ngx-darkbox-gallery/src/lib/model/darkbox-configuration.ts
> +   * SQUARE: A line of jumping squared moving in a wave like form
```suggestion
   * SQUARE: A line of jumping squares moving in a wave like form
```

2021-05-17 21:22 UTC, Boerni1995 commented on README.md
> +| loadingAnimation  | [LoadingAnimation](#LoadingAnimation) | Loading animation shown while the full sized image is loading|
```suggestion
| loadingAnimation  | [LoadingAnimation](#LoadingAnimation) | `LoadingAnimation.SPINNER` | Loading animation shown while the full sized image is loading|
```

2021-05-18 16:17 UTC, Boerni1995 approved these changes

2021-05-18 16:28 UTC, merged